#!/usr/bin/env bash
# model_inventory.sh — what the engine makes of every model in the collections.
#
#   scripts/model_inventory.sh [output.md] [root ...]
#
# Defaults: docs/model-inventory.md, over models/ G:/More-models H:/Models.
# This is the acceptance test for the architecture table in src/arch.cpp: it
# asks kraken-inspect (which asks the same verdict code the loader does) about
# every .gguf it can find, and writes one row per file plus a per-arch summary.
# A file whose arch is neither listed nor refused, or a table entry no file uses,
# shows up as a gap between the two.
#
# Runs no model: kraken-inspect reads metadata and the tensor directory only, so
# a 60 GB file costs the same as a 100 MB one.
set -u

out=${1:-docs/model-inventory.md}
shift || true

roots=("$@")
if [ ${#roots[@]} -eq 0 ]; then
    roots=(models "G:/More-models" "H:/Models")
fi

# Find the inspector next to this checkout's build first, then on PATH.
here=$(cd "$(dirname "$0")/.." && pwd)
inspect=""
for c in "$here/build-hip/kraken-inspect.exe" "$here/build-hip/kraken-inspect" \
         "$here/build/kraken-inspect" "$(command -v kraken-inspect 2>/dev/null)"; do
    if [ -n "$c" ] && [ -x "$c" ]; then inspect=$c; break; fi
done
if [ -z "$inspect" ]; then
    echo "model_inventory: build kraken-inspect first (ninja -C build-hip kraken-inspect)" >&2
    exit 2
fi

tmp=$(mktemp)
for root in "${roots[@]}"; do
    [ -d "$root" ] || continue
    find "$root" -maxdepth 3 -name '*.gguf' -type f | sort | while read -r f; do
        report=$("$inspect" "$f" --quant 2>&1)
        arch=$(printf '%s\n' "$report" | sed -n 's/^arch       //p')
        verdict=$(printf '%s\n' "$report" | sed -n 's/^verdict    //p')
        reasons=$(printf '%s\n' "$report" | sed -n 's/^ \{11\}- //p' | paste -sd '; ' -)
        notes=$(printf '%s\n' "$report" | sed -n 's/^ \{11\}\. //p' | paste -sd '; ' -)
        if [ -z "$arch" ]; then
            arch="$(printf '%s\n' "$report" | head -1 | sed 's/^kraken-inspect: //')"
            verdict="unreadable"
        fi
        size=$(du -m "$f" 2>/dev/null | cut -f1)
        printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
            "${arch}" "${verdict}" "${size:-?}M" "$f" "$reasons" "$notes" >> "$tmp"
    done
done

total=$(wc -l < "$tmp")
runnable=$(awk -F'\t' '$2 == "runnable"' "$tmp" | wc -l)

{
    echo "# Model inventory"
    echo
    echo "Generated by [scripts/model_inventory.sh](../scripts/model_inventory.sh) over"
    echo "\`${roots[*]}\` on $(date -u '+%Y-%m-%d')."
    echo
    echo "$total files, $runnable runnable. The verdict column is what the"
    echo "loader itself would decide (include/krk/verdict.hpp): an architecture in the"
    echo "table, a target role, formats this build can dequantize, and no tensor that names"
    echo "an unimplemented computation."
    echo
    echo "## By architecture"
    echo
    awk -F'\t' '{ split($1, a, " — "); key=a[1] "\t" $2; n[key]++ }
         END { for (k in n) printf "%s\t%d\n", k, n[k] }' "$tmp" |
        sort | awk -F'\t' '{ printf "- `%s` — %s: %d file(s)\n", $1, $2, $3 }'
    echo
    echo "## Files"
    echo
    echo "| arch | verdict | size | file | why not | notes |"
    echo "| --- | --- | --- | --- | --- | --- |"
    awk -F'\t' '{ gsub(/\|/, "\\|", $4);
         printf "| `%s` | %s | %s | %s | %s | %s |\n", $1, $2, $3, $4, $5, $6 }' "$tmp"
} > "$out"

rm -f "$tmp"
echo "model_inventory: $total files ($runnable runnable) -> $out"
